### ISSUE TITLE
D100 Do Not Display Critical Success or Critical Failure Icons

### ISSUE THREAD

**Issue by TenderLumpling** [cnharrison/dice-witch#14]
***_*MINOR VISUAL BUG*_***

As the title says.

When using a d100, the 'cs' and 'cf' commands do not display the images used to denote crit successes or failures. The image displays properly in all other instances (to my knowledge). Perhaps an issue with how d100s are displayed?

![image](https://user-images.githubusercontent.com/47048195/145665080-8ceda53a-d70d-4b97-ab72-54a99d5e6de2.png)

**Comment by cnharrison** [comment]
should be fixed now, thx for rreporting! https://github.com/cnharrison/dice-witch/commit/c9a37bb1375a02bf3d0e50cf272248d1c1b8030b
