### ISSUE TITLE
Dice Witch Bot, Issue

### ISSUE THREAD

**Issue by CatTheDemonHalo** [cnharrison/dice-witch#19]
The dice witch bit, was working perfectly all day except for astatring at the time of [("8:50pm, 2024 wensday, october 16th")]
My, and everyone in the server I am in, including all the servers my friend has the bot 
in, the Witch Bot would not respond it loaded, then keeped saying [("The application did not send")], I went on my tests server, tryed it it did the same thing, and still did the same thing even after, I kicked, and then re-joined the bot in to the server. Not sure if this, is because an update it's going through, but like to say it just incase, it's not known yet.

**Comment by cnharrison** [comment]
looks like there was a discord API  outage last night! bot is back up now
